global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'ollemg-monitoring'
rule_files:
  - /etc/prometheus/alert.rules
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - ollemg-monitoring.io:9093
      scheme: http
      timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - ollemg-monitoring.io:9090
 - job_name: alertmanager
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - ollemg-monitoring.io:9093
 - job_name: SNMP
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - ollemg-monitoring.io:9116
 - job_name: NODE
  metrics_path: /metrics
  scrape_interval: 10s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - ollemg-monitoring.io:9100
 - job_name: CAdvisor
  metrics_path: /metrics
  scrape_interval: 10s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - ollemg-monitoring.io:8080
 - job_name: 'netdata'
  metrics_path: '/api/v1/allmetrics'
  params:
    format: [prometheus]
  honor_labels: true
  scrape_interval: 5s
  static_configs:
      - targets: ['172.20.0.26:19999']