route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            title: '{{ template "custom_title" . }}'
            text: '{{ template "custom_slack_message" . }}'
            username: 'gabrielmello808@gmail.com'
            channel: '#monitoramento'
            api_url: 'https://hooks.slack.com/services/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'
            icon_url: https://avatars3.githubusercontent.com/u/3380462