route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: "gabrielmello808@gmail.com"
            channel: "#monitoramento"
            url: 'https://hooks.slack.com/services/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'
