global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'ollemg-monitoring'
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "ollemg_alertmanager:9093"

scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 5s
    static_configs:
        - targets: ['ollemg_prometheus:9090']
  - job_name: 'AlertManager'
    scrape_interval: 5s
    static_configs:
        - targets: ['ollemg_alertmanager:9093']
  - job_name: 'cAdvisor'
    scrape_interval: 5s
    static_configs:
        - targets: ['ollemg_cadvisor:8080']
  - job_name: 'NODE' 
    scrape_interval: 5s
    static_configs:
        - targets: ['ollemg_node-exporter:9100']
  # - job_name: 'SNMP'
  #   scrape_interval: 5s
  #   static_configs:
  #       - targets: ['ollemg_snmp-exporter:9116']
  - job_name: 'Netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['172.20.0.26:19999']
  - job_name: 'Alpine'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['172.20.0.23:19999']

