route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'email@email.com'
            channel: '#canal'
            api_url: 'WebHookDoSlack.com'
